spring.application.name=demo-driveflow

# --- Database connection ---
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:sqlserver://localhost:1433;databaseName=driveflow_assignment_db;encrypt=true;trustServerCertificate=true}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:driveflow_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:DriveFlow123!}
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.SQLServerDialect

# --- Spring Security active ---
# SecurityConfig handles authentication, registration and access guards.

# --- Spring Mail / SMTP Configuration (Mailtrap / SMTP for development) ---
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=0af319a3010b3f
spring.mail.password=39b04333cb570d
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000

