-- ============================================================================
-- DRIVEFLOW DATABASE MIGRATION SCRIPT - PART 02 UPDATES
-- ============================================================================

-- 1. DROP VEHICLE_ID FROM PROMOTION TABLE
-- Promotions are no longer tied to a single specific vehicle; they apply dynamically at checkout.
IF EXISTS (SELECT 1 FROM sys.foreign_keys WHERE name = 'fk_promotion_vehicle')
BEGIN
    ALTER TABLE promotion DROP CONSTRAINT fk_promotion_vehicle;
END
GO

IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('promotion') AND name = 'vehicle_id')
BEGIN
    ALTER TABLE promotion DROP COLUMN vehicle_id;
END
GO

-- 2. ADD PAYMENT_TYPE TO PAYMENT TABLE
-- Stores whether the customer chose 'CARD' or 'PAYPAL'
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('payment') AND name = 'payment_type')
BEGIN
    ALTER TABLE payment ADD payment_type VARCHAR(20) NULL;
END
GO

-- 3. CREATE PAYPAL_PAYMENT TABLE
-- Logs payments generated by the PayPal Strategy pattern
IF NOT EXISTS (SELECT 1 FROM sys.tables WHERE name = 'paypal_payment')
BEGIN
    CREATE TABLE paypal_payment (
        paypal_transaction_id VARCHAR(100) PRIMARY KEY,
        booking_id BIGINT NOT NULL,
        payer_email VARCHAR(150) NOT NULL,
        amount DECIMAL(10,2) NOT NULL CHECK (amount > 0),
        CONSTRAINT fk_paypal_booking FOREIGN KEY (booking_id) REFERENCES booking(booking_id) ON DELETE CASCADE
    );
END
GO

-- 4. VEHICLE_DOCUMENT ENHANCEMENTS FOR DIGITAL DOCUMENT UPLOADS
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('vehicle_document') AND name = 'file_name')
BEGIN
    ALTER TABLE vehicle_document ADD file_name VARCHAR(255) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('vehicle_document') AND name = 'file_path')
BEGIN
    ALTER TABLE vehicle_document ADD file_path VARCHAR(500) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('vehicle_document') AND name = 'uploaded_at')
BEGIN
    ALTER TABLE vehicle_document ADD uploaded_at DATE NULL DEFAULT CAST(GETDATE() AS DATE);
END
GO

-- 5. INSPECTION ENHANCEMENTS FOR ROUTINE FLEET INSPECTIONS
IF EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('inspection') AND name = 'booking_id' AND is_nullable = 0)
BEGIN
    ALTER TABLE inspection ALTER COLUMN booking_id BIGINT NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('inspection') AND name = 'vehicle_id')
BEGIN
    ALTER TABLE inspection ADD vehicle_id BIGINT NULL;
    ALTER TABLE inspection ADD CONSTRAINT fk_inspection_vehicle FOREIGN KEY (vehicle_id) REFERENCES vehicle(vehicle_id);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('inspection') AND name = 'inspection_date')
BEGIN
    ALTER TABLE inspection ADD inspection_date DATE NULL DEFAULT CAST(GETDATE() AS DATE);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('inspection') AND name = 'result')
BEGIN
    ALTER TABLE inspection ADD result VARCHAR(50) NULL;
END
GO

-- 6. HAS_DEPOSIT & REFUND ENHANCEMENTS FOR FINANCE ESCROW PANEL
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('has_deposit') AND name = 'deposit_date')
BEGIN
    ALTER TABLE has_deposit ADD deposit_date DATE NULL DEFAULT CAST(GETDATE() AS DATE);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('has_deposit') AND name = 'payment_method')
BEGIN
    ALTER TABLE has_deposit ADD payment_method VARCHAR(50) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('has_deposit') AND name = 'notes')
BEGIN
    ALTER TABLE has_deposit ADD notes VARCHAR(500) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('refund') AND name = 'reason')
BEGIN
    ALTER TABLE refund ADD reason VARCHAR(255) NULL;
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('refund') AND name = 'refund_date')
BEGIN
    ALTER TABLE refund ADD refund_date DATE NULL DEFAULT CAST(GETDATE() AS DATE);
END
GO

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('refund') AND name = 'booking_id')
BEGIN
    ALTER TABLE refund ADD booking_id BIGINT NULL;
    ALTER TABLE refund ADD CONSTRAINT fk_refund_booking FOREIGN KEY (booking_id) REFERENCES booking(booking_id);
END
GO

-- 7. USER IS_ACTIVE ACCESS CONTROL FLAG
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id = OBJECT_ID('users') AND name = 'is_active')
BEGIN
    ALTER TABLE users ADD is_active BIT NOT NULL CONSTRAINT df_users_is_active DEFAULT 1 WITH VALUES;
END
GO
